[package]
name = "client-cli"
version = "0.1.0"
authors = ["Devashish Dixit <devashish@crypto.com>"]
edition = "2018"

[dependencies]
chain-core = { path = "../chain-core" }
client-common = { path = "../client-common" }
client-index = { path = "../client-index" }
client-core = { path = "../client-core" }
structopt = "0.2"
failure = "0.1"
quest = "0.3"
secstr = "0.3.2"
hex = "0.3"
prettytable-rs = "0.8"
