[package]
name = "client-core"
version = "0.1.0"
authors = ["Devashish Dixit <devashish@crypto.com>"]
description = "This crate exposes following functionalities for interacting with Crypto.com Chain."
edition = "2018"

[dependencies]
chain-core = { path = "../chain-core" }
client-common = { path = "../client-common" }
client-index = { path = "../client-index" }
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "aa4f8e08253e7278c20122b9268c970d6f03d44c", features = ["serde", "zeroize", "rand", "recovery", "endomorphism", "musig"] }
rand = "0.6"
failure = "0.1"
hex = "0.3"
zeroize = "0.9"
byteorder = "1.3"
parity-codec = { features = ["derive"], version = "4.1.0" }
secstr = "0.3.2"
itertools = "0.8"
either = "1.5"

[dev-dependencies]
chrono = "0.4"
chain-tx-validation = { path = "../chain-tx-validation" }

[features]
default = ["sled", "rpc"]
sled = ["client-common/sled", "client-index/sled"]
rpc = ["client-index/rpc"]
