[package]
name = "dev-utils"
version = "0.1.0"
authors = ["Crypto.com <chain@crypto.com>"]
description = "Basic CLI for development purposes (e.g. generation of genesis.json parameters)"
edition = "2018"

[dependencies]
chain-core = { path = "../chain-core/" }
chain-abci = { path = "../chain-abci/" }
structopt = "0.2"
hex = "0.3"
failure = "0.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
kvdb-memorydb = "0.1"
